### ISSUE TITLE
RetinaFaceAntiConv convert to onnx error

### ISSUE THREAD

**Issue by zhouyongxyz** [linghu8812/tensorrt_inference#8]
按照这个操作步骤 python3 export_onnx.py  --prefix ./model/mnet_cov2 --network net3l

出现这个错误:
[16:35:30] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.5.0. Attempting to upgrade...
[16:35:30] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "export_onnx.py", line 280, in <module>
    main()
  File "export_onnx.py", line 276, in main
    [args.input_shape], np.float32, converted_onnx_filename)
  File "/home/haifan/haifan/anaconda3/lib/python3.7/site-packages/mxnet/contrib/onnx/mx2onnx/export_model.py", line 83, in export_model
    verbose=verbose)
  File "/home/haifan/haifan/anaconda3/lib/python3.7/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 312, in create_onnx_graph_proto
    checker.check_graph(graph)
  File "/home/haifan/haifan/anaconda3/lib/python3.7/site-packages/onnx/checker.py", line 53, in checker
    proto.SerializeToString(), ctx)
onnx.onnx_cpp2py_export.checker.ValidationError: Node (rf_c3_upsampling) has input size 2 not in range [min=3, max=4].

==> Context: Bad node spec: input: "rf_c3_lateral_relu" input: "rf_c3_upsamplingscales" output: "rf_c3_upsampling" name: "rf_c3_upsampling" op_type: "Resize" attribute { name: "mode" s: "nearest" type: STRING }

问一下，您这边的mxnet 版本是多少? 和 onnx 版本，我是 mxnet-cu102 1.6.0.post0

**Comment by linghu8812** [comment]
@zhouyongxyz onnx==1.5.0

**Comment by zhouyongxyz** [comment]
@linghu8812  Thank you very much. I use onnx 1.5.0 convert success.
