### ISSUE TITLE
export onnx error while converting .weights file to .onnx file in Yolov4 repo for csp model

### ISSUE THREAD

**Issue by chandu1263** [linghu8812/tensorrt_inference#86]
`Traceback (most recent call last):
  File "export_onnx.py", line 1112, in <module>
    neck=args.neck)
  File "export_onnx.py", line 1090, in main
    verbose=True)
  File "export_onnx.py", line 578, in build_onnx_graph
    params)
  File "export_onnx.py", line 429, in load_conv_weights
    conv_params, 'conv', 'weights')
  File "export_onnx.py", line 458, in _create_param_tensors
    conv_params, param_category, suffix)
  File "export_onnx.py", line 488, in _load_one_param_type
    buffer=self.weights_file.read(param_size * 4))
TypeError: buffer is too small for requested array`

What might be causing this error?
Any help would be great!

**Comment by akashAD98** [comment]
your weight file & cfg is not same, that's why your getting this error.
